Support eur/usd
tellor-io/telliot-feeds pull request #242
Opened 2022-07-19 16:28 UTC by tallywiesenberg

- Adds Coinbase and OpenExchangeRate Forex APIs as PriceServices
- Adds EUR/USD DataFeed, aggregating Coinbase and OpenExchangeRate
- Adds EUR/USD to QueryCatalog

2022-07-19 17:56 UTC, oraclown requested changes
Thanks @tallywiesenberg ! I left some change requests as comments

2022-07-19 17:56 UTC, oraclown commented on src/telliot_feeds/sources/price/currency/coinbase.py
> +        request_url = "/v2/exchange-rates?currency={}".format(asset.upper())
Use f-strings instead

2022-07-19 17:56 UTC, oraclown commented on src/telliot_feeds/sources/price/currency/coinbase.py
> +            raise Exception("Invalid response from get_url")
Don't raise an error. Catch specific ones, then have one that catches everything else you can't think of (and it should log an error. ex: `logger.error("Invalid response from get_url")`

2022-07-19 17:56 UTC, oraclown commented on src/telliot_feeds/sources/price/currency/coinbase.py
> +        price = float(response["data"]["rates"][currency.upper()])
Is it possible to get a `KeyError` here?

2022-07-19 17:56 UTC, oraclown commented on src/telliot_feeds/sources/price/currency/openexchangerate.py
> +        request_url = "/v6/latest/{}".format(asset.upper())
Use f-string instead

2022-07-19 17:56 UTC, oraclown commented on src/telliot_feeds/sources/price/currency/openexchangerate.py
> +            raise Exception("Invalid response from get_url")
Same thing re raising errors as above. We wan't `telliot` to keep running, but just log the error

2022-07-19 17:56 UTC, oraclown commented on src/telliot_feeds/sources/price/currency/openexchangerate.py
> +        price = float(response["rates"][currency.upper()])
Same thing re `KeyError` as above

2022-07-19 17:56 UTC, oraclown commented on tests/feeds/test_eur_usd_feed.py
> +def test_query_info():
You can remove this test. `SpotPrice` query generation of its `queryId` & `queryData` has been tested. If you want to include the `queryId` & `queryData` somewhere in the file w/ the datafeed (as a docstring or comment), then that's an option

2022-07-19 17:57 UTC, oraclown commented
> 

You need to change the function return types to match what it's telling you the function outputs

2022-07-19 17:58 UTC, oraclown commented
> Tox typing failing on... ` src/telliot_feeds/reporters/reporter_autopay_utils.py:166: error: Returning Any from function declared to return "Optional[int]"` `src/telliot_feeds/cli/commands/report.py:397: error: Function does not return a value`

You need to change the function return types to match what it's telling you the function outputs

2022-07-19 20:04 UTC, oraclown approved these changes
Nice, thanks @tallywiesenberg

2022-07-19 20:07 UTC, oraclown commented on src/telliot_feeds/sources/price/currency/openexchangerate.py
> +                logger.error("Invalid response from get_url")
Need to return None, None here I think?

2022-07-19 20:07 UTC, oraclown requested changes
Left some comments and your tests are failing:
```
FAILED tests/feeds/test_eur_usd_feed.py
FAILED tests/sources/test_curr_exchange_sources.py
  ```

2022-07-20 15:46 UTC, tallywiesenberg commented
test passing!

2022-07-21 14:00 UTC, oraclown approved these changes

2022-07-21 14:01 UTC, merged