add pulsechain
tellor-io/telliot-feeds pull request #282
Opened 2022-08-05 16:52 UTC by tallywiesenberg

Closes #281

2022-08-08 13:27 UTC, oraclown approved these changes
Thanks @tallywiesenberg ! Make sure to post an example tx like I mentioned in the issue

2022-08-08 13:30 UTC, oraclown approved these changes
Thanks @tallywiesenberg ! Make sure to include tx I mentioned in the issue

cc @akremstudy . Does the multicall addition look fine?

2022-08-08 13:42 UTC, tallywiesenberg commented
converted to draft until data source test passes

2022-08-16 18:19 UTC, oraclown requested changes
Thanks @tallywiesenberg . Small logging change needed

2022-08-16 18:19 UTC, oraclown commented on src/telliot_feeds/sources/price/spot/pulsechain_subgraph.py
> +            except Exception as e:
You want to include the specific error `e` in the log msg here, since we'll want to Except the specific ones as they are discovered

2022-08-17 13:58 UTC, tallywiesenberg commented
Pulsechain subgrpah TX on pulsechain testnet https://scan.v2b.testnet.pulsechain.com/tx/0xac724e53e1de094faa320ad66ece6f3e426335d2843bceda644d183568215348/internal-transactions

2022-08-17 14:15 UTC, tallywiesenberg commented
Closes #281 Closes #283

2022-08-17 15:25 UTC, oraclown requested changes
Thanks @tallywiesenberg ! Some clarification needed and a small logging change

2022-08-17 15:25 UTC, oraclown commented on src/telliot_feeds/sources/price/spot/pulsechain_subgraph.py
> +            except Exception:
You want to include the unknown error in the logging message, so use `e` actually. Also elevate the logging level to ERROR

2022-08-17 15:25 UTC, oraclown commented on src/telliot_feeds/sources/price/spot/bittrex.py
> +            if "JSON Decode Error" in d["error"]:
What's this about? What error were you getting?

2022-08-17 18:17 UTC, oraclown commented on src/telliot_feeds/sources/price/spot/bittrex.py
> +            if "JSON Decode Error" in d["error"]:
Oh, Closes: #304

2022-08-17 18:33 UTC, oraclown approved these changes

2022-08-17 18:35 UTC, merged