include 360 on rinkeby reporting
tellor-io/telliot-feeds pull request #396
Opened 2022-10-07 15:41 UTC by akremstudy

### Summary
- refactored cli/commands/report.py to enable 360 Flex reporting on rinkeby.
- also edited the reporter_utils.py file to handle function signature differences in 360 and Tellorx Oracles

### Steps Taken to QA Changes
- staked and reported on rinkeby. Txn hash: 0x38bb5872a070870cb805086b695dd0831ca7ea75cb6c0609f99fb00d802c346f. Has to be checked manually since rinkeby etherscan has been deprecated.

- further testing later

### Checklist
This pull request is:

- [ ] A documentation error, docs update, or typographical error fix
	- No tests or issue needed
- [ ] A code fix
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. Fixes without tests will not be accepted unless it's related to the documentation only.
    - Please make sure docs are updated if need be
- [ ] A feature implementation
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

2022-10-07 16:01 UTC, oraclown requested changes
Thanks @akremstudy . I added some questions/suggestions

2022-10-14 16:48 UTC, oraclown approved these changes
Awesome @akremstudy , ty!

Are reporting tests passing for diva/rng updated reporters?

2022-10-14 16:48 UTC, oraclown commented on src/telliot_feeds/cli/commands/report.py
> +            # Type 2 transactions unsupported currently
Why?

2022-10-14 16:54 UTC, akremstudy commented on src/telliot_feeds/cli/commands/report.py
> +            # Type 2 transactions unsupported currently
idk that was from something previous

2022-10-14 20:49 UTC, akremstudy commented
> Awesome @akremstudy , ty!
> 
> Are reporting tests passing for diva/rng updated reporters?

yes they are

2022-10-14 20:51 UTC, merged