Consolidate
tellor-io/telliot-feeds pull request #684
Opened 2023-06-11 16:38 UTC by akremstudy

### Summary

### Steps Taken to QA Changes

### Checklist

This pull request is:

- [ ] A documentation error, docs update, or typographical error fix
	- No tests or issue needed
- [ ] A code fix
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. Fixes without tests will not be accepted unless it's related to the documentation only.
    - Please make sure docs are updated if need be
- [ ] A feature implementation
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

2023-06-26 17:26 UTC, akremstudy commented
@oraclown, Can I get a review on this pr specifically these two files [reporter](https://github.com/tellor-io/telliot-feeds/blob/e832beb7787d53716c4de5768447237306c5d77f/src/telliot_feeds/reporters/tellor_360.py) and [GasFees](https://github.com/tellor-io/telliot-feeds/blob/e832beb7787d53716c4de5768447237306c5d77f/src/telliot_feeds/reporters/gas.py).  Made a lot of changes but those are the main ones, if you can review them first then I can make changes before you spend time on the other files.

2023-07-06 12:03 UTC, oraclown requested changes
Thanks, @akremstudy ! Awesome refactoring of the reporter. Huge. I has some minor suggestions. Some tests needed for the new cli commands. I'd also encourage posting some example txs using the new cli commands, as well as just reporting, just as a sanity check. Great cli additions and updates to gas fees calculation code!

2023-07-18 03:44 UTC, akremstudy commented on src/telliot_feeds/cli/commands/request_withdraw_stake.py
> +    ctx.obj["CHAIN_ID"] = accounts[0].chains[0]  # used in reporter_cli_core
if no accounts it exits

2023-07-18 03:45 UTC, akremstudy commented on src/telliot_feeds/reporters/tellor_360.py
> +        - (int, ResponseStatus) the current stake amount in TellorFlex
yeah

2023-07-18 03:45 UTC, akremstudy commented on src/telliot_feeds/utils/stake_info.py
> +    def stake_amount_change(self) -> bool:
same

2023-07-18 03:45 UTC, akremstudy commented on src/telliot_feeds/utils/stake_info.py
> +            if self.staker_balance_history[-1] < self.staker_balance_history[-2]:
it shouldn't since it checks if list length is 2 first.

2023-07-19 18:15 UTC, 0xSpuddy commented
Testing by running a reporter on each testnet listening for tips / reporting at regular intervals. I haven't tested every combination of flags, but no errors so far.

2023-07-26 14:06 UTC, oraclown approved these changes
Thanks for the updates, @akremstudy !

2023-08-02 13:07 UTC, merged